餐廳名稱          {{$coupons->name}}<br>
優惠卷抬頭            {{$coupons->title}}<br>
優惠卷內容          {{$coupons->content}}<br>
照片        {{$coupons->photo}}<br>
折扣         {{$coupons->discount}}<br>
扣多少錢         {{$coupons->lowestprice}}<br>
使用狀態         {{$coupons->status}}<br>
可以開始使用的日期        {{$coupons->StartTime}}<br>
結束日期           {{$coupons->EndTime}}<br>